### ISSUE TITLE
Moving away from Planetscale

### ISSUE THREAD

**Issue by albugowy15** [albugowy15/informatics-frs-helper#147]
Planetscale has announced that they will be discontinuing the Hobby (Free) plan starting April 8th. To continue using the database, users will need to switch to a Paid plan.

Now, I am looking for an alternative MySQL compatible database service that offers a free plan.

**Comment by hooopo** [comment]
You can try TiDB Serverless: https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-nextjs

**Comment by albugowy15** [comment]
Done #148
